name: webgenius
description: "A new Flutter project."
publish_to: 'none' # Private package, not for pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  flutter_screenutil: ^5.9.3
  image_picker: ^1.0.4
  dotted_border: ^2.0.0
  provider: ^6.1.5+1
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  flutter_gen_runner: any

flutter_gen:
  output: lib/gen/
  line_length: 80
  colors:
    inputs:
      - assets/color/colors.xml
    outputs:
      class_name: AppColors

flutter:
  uses-material-design: true

  assets:
    - assets/color/
    - assets/images/
    - assets/icons/
    - assets/icons/backbutton_icon.svg
